name: Actions Workflow
on: [push]
jobs:
  run_hola_mundo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        id: hello
        uses: grilosystems/hola-mundo-js-actionsgs@v1
        with:
          who-to-greet: Marquito
      - name: Tiempo de Saludo
        run: echo "${{ steps.hello.outputs.time }}"