name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: paso inicial
        run: echo "Terminado"
      - name: software versions
        run: |
          node -v
          npm -v
      - name: comando python
        run: |
          import platform
          print(platform.processor())
        shell: python
